$LOAD_PATH.unshift('../lib')
require 'config'

require 'berkshelf/vagrant'

Vagrant::Config.run do |config|
  # config.berkshelf.berksfile_path = "./Berksfile"
  # config.berkshelf.only = []
  # config.berkshelf.except = []

  config.vm.host_name = "chef-10"

  config.vm.box     = Environment::Config[:base_box]
  config.vm.box_url = Environment::Config[:base_box_url]
  config.vm.network :hostonly, Environment::Config[:chef_10_ip_addr]

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      'chef-server' =>
      {
        url: "http://#{Environment::Config[:chef_10_ip_addr]}:4000",
        webui_enabled: true,
      },
      setup: {
        chef_server_version: 'chef-10'
      }

    }

    chef.run_list = [ "apt", "chef-server::rubygems-install", "setup::knife" ]
  end


  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  config.ssh.max_tries = 40
  config.ssh.timeout   = 120
end
